name: mlf
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=11.6
  - cudnn=8.*
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu116
    - -r requirements.txt
